### PR TITLE
add lytics.io segment definition

### PR DESCRIPTION
**Pull request by markhayden**
segment definition for lytics.io / getlytics.com primary data collection tag.

### CODE REVIEW

**Comment by stevenmiller888** [comment]
@markhayden Awesome! From what I see [here](https://segment.com/docs/integrations/lytics/#settings), it doesn't seem like the Tag ID or Stream are used, right? If the API Key isn't accessible via the `config` object, the plugin could probably just return the  `cid`. Does that make sense?

**Comment by markhayden** [comment]
@stevenmiller888 yep that makes total sense. the stream and tag id are coming out in an upcoming update so was just adding them ahead of time. pulled them for now so we just return cid, which is the equivalent of an "account id". thanks!

**Comment by stevenmiller888** [comment]
@markhayden Great! Also, just noticed you didn't add any tests. Do you mind adding `test/fixtures/lytics/index.html` and `test/lib/lytics.js`? Just want to make sure we keep everything well-tested as we add new plugins :)

**Comment by markhayden** [comment]
no problem, I should have done that anyway :). added in tests.

**Comment by dominicbarnes** [comment]
Looks great to me! Thanks @markhayden

**Comment by markhayden** [comment]
thanks, stoked to start playing with sherlock, good work all!

**Pull request merged**
